version: '9'
name: Android Open Source Project
type: release
variant: user
datetime: 1555835843
host: android
user: build
platform:
  ref: android-9.0.0_r35
  extra_remotes:
  - name: github
    fetch: https://github.com/
  extra_projects:
  - name: anestisb/android-prepare-vendor
    groups: device
    path: vendor/android-prepare-vendor
    remote: github
    revision: refs/heads/master
  remove_paths:
  - platform/prebuilts/qemu-kernel
  - platform/developers/samples/android
  - platform/developers/demos
  - device/generic/car
  - device/generic/qemu
  - device/generic/goldfish
  - device/generic/goldfish-opengl
  - device/lenaro/bootloader/arm-trusted-firmware
  - device/lenaro/bootloader/edk2
  - device/lenaro/bootloader/OpenPlatformPkg
  - device/lenaro/hikey
  - device/lenaro/hikey-kernel
  - device/lenaro/
  - device/google/atv
  - device/google/contexthub
  - device/google/cuttlefish
  - device/google/cuttlefish_kernel
  - device/google/cuttlefish_sepolicy
  - device/google/cuttlefish_common
  - device/google/muskie
  - device/generic/mips
  - device/google/hikey-kernel
  - device/generic/mips64
  - device/generic/mini-emulator-arm64
  - device/generic/mini-emulator-armv7-a-neon
  - device/generic/mini-emulator-mips
  - device/generic/mini-emulator-mips64
  - device/generic/mini-emulator-x86
  - device/generic/mini-emulator-x86_64
  - device/google/accessory/arduino
  - device/google/accessory/demokit
  remove_groups:
  - darwin
devices:
  crosshatch:
    global:
      kernel_name: bluecross
      kernel_ref: origin/android-msm-bluecross-4.9-pie-qpr1
      kernel_repo: kernel/manifest
      avb_mode: vbmeta_chained
      factory_build: PQ3A.190505.002
      factory_hash: 99879eba8020ad35c69a90f3b3d4443e857283d51deec33cd644da5c645e5f5a
    verizon:
      factory_hash: 7e9da376a846c934eb3b4ca39833996ee453c3ad67bb23a365ba09862c286d03
      factory_build: PD1A.180720.031
    docomo:
      factory_build: PQ1A.181205.006.A1
      factory_hash: 99bead334525f4d26ef5777ebc910648674597e1322a2a95e9e2d4f9df5d69cf
  blueline:
    global:
      kernel_name: bluecross
      kernel_ref: origin/android-msm-bluecross-4.9-pie-qpr1
      kernel_repo: kernel/manifest
      avb_mode: vbmeta_chained
      factory_build: PQ3A.190505.002
      factory_hash: 26d2002511d6a13fc523334b7f783dd757edd543179c7a5dc2f7e1d322efc6e3
    verizon:
      factory_build: PD1A.180720.031
      factory_hash: 3df41a2b65335bb6c130f36b0bbd87c3f90822b7ef04f210232daacc3693142a
    docomo:
      factory_build: PQ1A.181205.006.A1
      factory_hash: e0442d3b0a9e5636f4979b5780b6173635fe73917e88ffe1b9d36c2bc45aa7bc
  taimen:
    global:
      kernel_name: wahoo
      kernel_ref: android-msm-wahoo-4.4-pie-qpr1
      kernel_repo: kernel/msm
      avb_mode: vbmeta_simple
      factory_build: PQ3A.190505.001
      factory_hash: f91e5af8dd8675c737b78b03c60143c14e78155d1561115a9ec1a5e3a6aacc58
    telstra:
      factory_build: PPR1.180610.011
      factory_hash: 9f0cb004c3b42789c150293aa6a6eecb0f289324ce1403befde93b106da59829
  walleye:
    global:
      kernel_name: wahoo
      kernel_ref: android-msm-wahoo-4.4-pie-qpr1
      kernel_repo: kernel/msm
      avb_mode: vbmeta_simple
      factory_build: PQ3A.190505.001
      factory_hash: d2730d9cd155ada199c7c9d90eebb4e43cc7e2702f6853e59e2f79d4be6be291
    telstra:
      factory_build: PPR1.180610.011
      factory_hash: 0fbd304845b6a1e8c5960deedb70aab0f804a4b1bb93242b3bbcdad586982769
  marlin:
    global:
      kernel_name: marlin
      kernel_ref: android-msm-marlin-3.18-pie-qpr1-s2
      kernel_repo: kernel/msm
      avb_mode: verity_only
      factory_build: PQ3A.190505.001
      factory_hash: 5dac573cedb98a1c8b8e9cf0bf87710e9f0d32a4290ed2339412fdc437fca331
    telus:
      factory_build: PPR1.181005.003.A1
      factory_hash: 960a173f0f84e2c3c0c5d96643e6ca3f99d5a898a932c6e3a62c52282d6fb3f4
    verizon:
      factory_build: PPR2.180905.006.A1
      factory_hash: a78fe26434e04f8d5015bab79f717fc7b03b13286370b079b7e96d1f7562512a
  sailfish:
    global:
      kernel_name: marlin
      kernel_ref: android-msm-marlin-3.18-pie-qpr1-s2
      kernel_repo: kernel/msm
      avb_mode: verity_only
      factory_build: PQ3A.190505.001
      factory_hash: f3d2032d0862961a1712445226f942f7f430851fbbac045b724cffafaa5c6e83
    telus:
      factory_build: PPR1.181005.003.A1
      factory_hash: 6a2c3b69a43f93e576f953d7c8368648bd26f7d23667556a65af40282a72f7af
    verizon:
      factory_build: PPR2.180905.006.A1
      factory_hash: b063909b211beea28e6879a12db1dade1eb4c007900082c10ea160f15c6feae7
