version: '11'
name: Android Open Source Project
type: release
variant: user
datetime: 1606063413
host: android
user: build
build_kernel: true
platform:
  extra_remotes:
  - name: GrapheneOS
    fetch: https://github.com/GrapheneOS
  extra_projects:
  - name: android-prepare-vendor
    groups: device
    path: vendor/android-prepare-vendor
    remote: GrapheneOS
    revision: refs/heads/11
  remove_paths:
  - device/generic/car
  - device/generic/mini-emulator-arm64
  - device/generic/mini-emulator-armv7-a-neon
  - device/generic/mini-emulator-x86
  - device/generic/mini-emulator-x86_64
  - device/generic/qemu
  - device/google/atv
  - device/google/contexthub
  - device/google/crosshatch-kernel
  - device/google/muskie
  - device/google/wahoo-kernel
  - device/lenaro/bootloader/arm-trusted-firmware
  - device/linaro/bootloader/OpenPlatformPkg
  - device/linaro/bootloader/arm-trusted-firmware
  - device/linaro/bootloader/edk2
  - device/linaro/dragonboard
  - device/linaro/dragonboard-kernel
  - device/linaro/poplar
  - device/linaro/poplar-kernel
  - platform/developers/demos
  - platform/developers/samples/android
  - platform/prebuilts/qemu-kernel
  remove_groups:
  - darwin
devices:
  bonito:
    kernel_ref: origin/android-msm-bluecross-4.9-pie-qpr1
    build_id: RP1A.201105.002
    factory_hash: 30f25dd2b0049915da8fd45c42c9b56becbebcba54adcb2af56e68d6d1cb357f
    ota_hash: b5852e2a7234dc9220634f5fc197ae324780be6323e2e07ef687355671520e87
    platform_ref: android-11.0.0_r17
  sargo:
    kernel_ref: origin/android-msm-bluecross-4.9-pie-qpr1
    build_id: RP1A.201105.002
    factory_hash: 2433e0c0574d731c103951d16164bd2502b34d386e2ab12082f686c784c3929c
    ota_hash: cd4ef64b5f052acbf0c19c0532f254c53c4902ec862db26a6d7ddb853103de7e
    platform_ref: android-11.0.0_r17
  crosshatch:
    kernel_ref: origin/android-msm-bluecross-4.9-pie-qpr1
    avb_mode: vbmeta_chained
    build_id: RP1A.201105.002
    factory_hash: c60d8b3ab2960bf3bff25985f0c64447f4b4e111a71017e0128669fc49a80cac
    ota_hash: 9315242f00af51e42ac9309a8ec3cfc18b9165b59d0635f2217feaf4aeacd78e
    platform_ref: android-11.0.0_r17
  blueline:
    kernel_ref: origin/android-msm-bluecross-4.9-pie-qpr1
    avb_mode: vbmeta_chained
    build_id: RP1A.201105.002
    factory_hash: 0347d8cd0a70609ebb46f62f635b6d8d91435312b37eed6df17eff02e9aec34c
    ota_hash: 8dd4eb5b0f0d4ae0c33833fa48082b077f67e1069e07736f73568cc512119564
    platform_ref: android-11.0.0_r17
  taimen:
    kernel_ref: origin/android-msm-wahoo-4.4-pie-qpr2
    avb_mode: vbmeta_simple
    build_id: RP1A.201005.004
    factory_hash: f797c86c31a79d2f219a8a75e643899fa3576cefca9245314aa87fe80a1f04e2
    ota_hash: b5dff51e9891236ea84bb1027614d6e9c8a4ad59f0a35275a9e0ff14f946a70c
    platform_ref: android-10.0.0_r21
  walleye:
    kernel_ref: origin/android-msm-wahoo-4.4-pie-qpr2
    avb_mode: vbmeta_simple
    build_id: RP1A.201005.004
    factory_hash: 78b8d156a944a5664f366ea75f78068e45a8000d112a4a48fe1402a24b7aadf9
    ota_hash: 6efaff496f25b06961b92c562ae748007fafdfb92b45db4e3e59d5c741f67e58
    platform_ref: android-10.0.0_r21
