version: '10'
name: Android Open Source Project
type: release
variant: user
datetime: 1580638177
host: android
user: build
build_kernel: true
platform:
  extra_remotes:
  - name: github
    fetch: https://github.com
  extra_projects:
  - name: hashbang/android-prepare-vendor
    groups: device
    path: vendor/android-prepare-vendor
    remote: github
    revision: refs/heads/10.0
  remove_paths:
  - platform/prebuilts/qemu-kernel
  - platform/developers/samples/android
  - platform/developers/demos
  - device/generic/car
  - device/generic/qemu
  - device/lenaro/bootloader/arm-trusted-firmware
  - device/lenaro/bootloader/edk2
  - device/lenaro/bootloader/OpenPlatformPkg
  - device/lenaro/hikey
  - device/lenaro/hikey-kernel
  - device/lenaro/
  - device/google/atv
  - device/google/contexthub
  - device/google/muskie
  - device/google/marlin
  - device/generic/mips
  - device/google/hikey-kernel
  - device/generic/mips64
  - device/generic/mini-emulator-arm64
  - device/generic/mini-emulator-armv7-a-neon
  - device/generic/mini-emulator-mips
  - device/generic/mini-emulator-mips64
  - device/generic/mini-emulator-x86
  - device/generic/mini-emulator-x86_64
  - device/google/accessory/arduino
  - device/google/accessory/demokit
  remove_groups:
  - darwin
devices:
  bonito:
    kernel_ref: origin/android-msm-bluecross-4.9-pie-qpr1
    build_id: QQ1A.200105.002
    factory_hash: 3169d39601cf5e2bbec9680c244365e132903c8e3df7b1ca05629b4e94688a0d
    ota_hash: 592a20ac4d8c537c65a473efd2679b4bfd70fb9887fb588460524345d6ddcfee
    platform_ref: android-10.0.0_r21
  sargo:
    kernel_ref: origin/android-msm-bluecross-4.9-pie-qpr1
    build_id: QQ1A.200105.002
    factory_hash: 0c3e12c2499d8132bd4e21772c4028c24e993852abe0622e025a7325a555ef73
    ota_hash: 3316c5ea9842f7634be3835a79ae34daa1aa02b0063fc45a86f9c96d6bb9e771
    platform_ref: android-10.0.0_r21
  crosshatch:
    kernel_ref: origin/android-msm-bluecross-4.9-pie-qpr1
    avb_mode: vbmeta_chained
    build_id: QQ1A.200105.003
    factory_hash: 6d235f477ac74153bf8bc23e69e30c81cb500ca2ac72a3d67731f916981dacea
    ota_hash: d156e29c1c0d3af19fd9795bb8bf63c60ff15ac0fc7328aded7cb3c6e53bb7b8
    platform_ref: android-10.0.0_r22
  blueline:
    kernel_ref: origin/android-msm-bluecross-4.9-pie-qpr1
    avb_mode: vbmeta_chained
    build_id: QQ1A.200105.003
    factory_hash: 8e0fc70e8d598ce753b8e3a9ef77381293af63ea0e91c9c72837233b2d2eb14e
    ota_hash: f758eeb5738a9f7d586b569ef0ed18b2223c076f6b1f980de159f6e183b1fd7b
    platform_ref: android-10.0.0_r22
  taimen:
    kernel_ref: origin/android-msm-wahoo-4.4-pie-qpr2
    avb_mode: vbmeta_simple
    build_id: QQ1A.200105.002
    factory_hash: 10d1c3227e4e37994386f6d5940a2a6a973ceba423369a75200e7f2fb6a5f915
    ota_hash: 150a82f7593456769f85dd031673f1b8612be4e766a5d7524bdcd3ffc5186a45
    platform_ref: android-10.0.0_r21
  walleye:
    kernel_ref: origin/android-msm-wahoo-4.4-pie-qpr2
    avb_mode: vbmeta_simple
    build_id: QQ1A.200105.002
    factory_hash: 877e8ab1131301ef680056e45ca40a87421a72833d53fda87ed00fadb1fe7480
    ota_hash: cfc5642bb00103ecbf8315420834ab3d346f14feba3f14c650d503b688c3fa97
    platform_ref: android-10.0.0_r21
