version: '11'
name: Android Open Source Project
type: release
variant: user
datetime: 1614712499
host: android
user: build
build_kernel: true
platform:
  extra_remotes:
  - name: grapheneos
    fetch: https://github.com/GrapheneOS
  extra_projects:
  - name: android-prepare-vendor
    groups: device
    path: vendor/android-prepare-vendor
    remote: grapheneos
    revision: refs/heads/11
  remove_paths:
  - device/generic/car
  - device/generic/mini-emulator-arm64
  - device/generic/mini-emulator-armv7-a-neon
  - device/generic/mini-emulator-x86
  - device/generic/mini-emulator-x86_64
  - device/generic/qemu
  - device/google/atv
  - device/google/contexthub
  - device/google/crosshatch-kernel
  - device/google/muskie
  - device/google/wahoo-kernel
  - device/lenaro/bootloader/arm-trusted-firmware
  - device/linaro/bootloader/OpenPlatformPkg
  - device/linaro/bootloader/arm-trusted-firmware
  - device/linaro/bootloader/edk2
  - device/linaro/dragonboard
  - device/linaro/dragonboard-kernel
  - device/linaro/poplar
  - device/linaro/poplar-kernel
  - platform/developers/demos
  - platform/developers/samples/android
  - platform/prebuilts/qemu-kernel
  - prebuilts/android-emulator
  remove_groups:
  - beagle_x15
  - darwin
  - mips
  - yukawa
devices:
  bonito:
    kernel_ref: android-msm-bluecross-4.9-pie-qpr1
    build_id: RQ2A.210305.006
    factory_hash: ad2aeddc927eec804fd9e93638199a96c6accd7922688e172011861b939e9479
    ota_hash: 3a8feca9608ced4ab4d860bdd8f3a9f99d1e74c27b597166170649624514abb9
    platform_ref: android-11.0.0_r32
    platform_pubkey: aosp.asc
  sargo:
    kernel_ref: android-msm-bonito-4.9-android11
    build_id: RQ2A.210305.006
    factory_hash: c553e4a1e53da7e4c5edf0c5c6aa0669d42ad97b3ea103a97cb9e322b25dbbcd
    ota_hash: 39e6ff3dec4800d84ccb2500a339ceb8076922dc0c28d26d89f2f8131a6c932b
    platform_ref: android-11.0.0_r32
    platform_pubkey: aosp.asc
  crosshatch:
    kernel_ref: android-msm-bluecross-4.9-pie-qpr1
    avb_mode: vbmeta_chained
    build_id: RQ2A.210305.006
    factory_hash: 92a7de4f4c47b01477b275fe96630e90e9aea765db1dd8a05f98e88c6ec8983c
    ota_hash: c6f501ceb5d2468d1326d190d0085c08fd47ce12b51f93ab5f30d74cd76cad87
    platform_ref: android-11.0.0_r32
    platform_pubkey: aosp.asc
  blueline:
    kernel_ref: android-msm-bluecross-4.9-pie-qpr1
    avb_mode: vbmeta_chained
    build_id: RQ2A.210305.006
    factory_hash: b4a2f36e9e9df4f711c325c1d03d3841f974174dc2796a7f2e44e9b24fa89c8b
    ota_hash: b94faf09eec09855242c5ebf08ec2668caeebfd3a1052758e0f0da3bfe8582c7
    platform_ref: android-11.0.0_r32
    platform_pubkey: aosp.asc
  taimen:
    kernel_ref: android-msm-wahoo-4.4-pie-qpr2
    avb_mode: vbmeta_simple
    build_id: RP1A.201005.004.A1
    factory_hash: 2f5c4987a8e1c29bb2843d7f7d36721d52f2eb25a0fe4c74b3590e34a06eb44f
    ota_hash: 9de3b96223cf14e8afd69ed9b21b801a15a96990781a7058ac8418ffd78e0dd7
    platform_ref: android-11.0.0_r25
    platform_pubkey: aosp.asc
  walleye:
    kernel_ref: android-msm-wahoo-4.4-pie-qpr2
    avb_mode: vbmeta_simple
    build_id: RP1A.201005.004.A1
    factory_hash: 0c23f6cf9e2194a3e72b1288f65c5a7f2f6c020080af49c8a494ee99ab3eb543
    ota_hash: ccd1069bde76fc2ef3414d619ddb5fb840addae955e85d9829df9a7e8d2484a9
    platform_ref: android-11.0.0_r25
    platform_pubkey: aosp.asc
