version: '11'
name: Android Open Source Project
type: release
variant: user
datetime: 1620160617
host: android
user: build
build_kernel: true
platform:
  extra_remotes:
  - name: grapheneos
    fetch: https://github.com/GrapheneOS
  extra_projects:
  - name: android-prepare-vendor
    groups: device
    path: vendor/android-prepare-vendor
    remote: grapheneos
    revision: refs/heads/11
  remove_paths:
  - device/generic/car
  - device/generic/mini-emulator-arm64
  - device/generic/mini-emulator-armv7-a-neon
  - device/generic/mini-emulator-x86
  - device/generic/mini-emulator-x86_64
  - device/generic/qemu
  - device/google/atv
  - device/google/contexthub
  - device/google/crosshatch-kernel
  - device/google/muskie
  - device/google/wahoo-kernel
  - device/lenaro/bootloader/arm-trusted-firmware
  - device/linaro/bootloader/OpenPlatformPkg
  - device/linaro/bootloader/arm-trusted-firmware
  - device/linaro/bootloader/edk2
  - device/linaro/dragonboard
  - device/linaro/dragonboard-kernel
  - device/linaro/poplar
  - device/linaro/poplar-kernel
  - platform/developers/demos
  - platform/developers/samples/android
  - platform/prebuilts/qemu-kernel
  - prebuilts/android-emulator
  remove_groups:
  - beagle_x15
  - darwin
  - mips
  - yukawa
devices:
  bonito:
    kernel_ref: android-msm-bluecross-4.9-pie-qpr1
    build_id: RQ2A.210505.002
    factory_hash: eca5fd06f5a4ab60165a0f101d6e6f80213923aa6a2f239e418ec810fd03bec5
    ota_hash: ae4097d4b2d5112fca1f4c58d22e5ccf19d8b1ee2ed5c8d10632cc80da8626ac
    platform_ref: android-11.0.0_r36
    platform_pubkey: aosp.asc
  sargo:
    kernel_ref: android-msm-bonito-4.9-android11
    build_id: RQ2A.210505.002
    factory_hash: aca757e9ca25471aca3ac6ef85ebf4eb5cb0db1b81a38a592c6dddcba6714646
    ota_hash: c70e930148a2ebb59e153bf832829142ec9f5db632dc9c44a446525428f8ee7b
    platform_ref: android-11.0.0_r36
    platform_pubkey: aosp.asc
  crosshatch:
    kernel_ref: android-msm-bluecross-4.9-pie-qpr1
    avb_mode: vbmeta_chained
    build_id: RQ2A.210505.002
    factory_hash: 796587eec0e5c01d3f6bfdd8bc006b54d1d932169902e67934568b64b650995f
    ota_hash: 594ba48d5dc59c088a539b9a6d1987f29ecd1fee7b8bf8ebc92d1be930e3f815
    platform_ref: android-11.0.0_r36
    platform_pubkey: aosp.asc
  blueline:
    kernel_ref: android-msm-bluecross-4.9-pie-qpr1
    avb_mode: vbmeta_chained
    build_id: RQ2A.210505.002
    factory_hash: 687d8468ec80530140148d75c8971930398267b8d1e20ef89edebc1f4db7e988
    ota_hash: 7fe7bb9bf38cd3333cf1dd18aec607489e10c13405afdaf810c1fcda2a05c9d2
    platform_ref: android-11.0.0_r36
    platform_pubkey: aosp.asc
  taimen:
    kernel_ref: android-msm-wahoo-4.4-pie-qpr2
    avb_mode: vbmeta_simple
    build_id: RP1A.201005.004.A1
    factory_hash: 2f5c4987a8e1c29bb2843d7f7d36721d52f2eb25a0fe4c74b3590e34a06eb44f
    ota_hash: 9de3b96223cf14e8afd69ed9b21b801a15a96990781a7058ac8418ffd78e0dd7
    platform_ref: android-11.0.0_r25
    platform_pubkey: aosp.asc
  walleye:
    kernel_ref: android-msm-wahoo-4.4-pie-qpr2
    avb_mode: vbmeta_simple
    build_id: RP1A.201005.004.A1
    factory_hash: 0c23f6cf9e2194a3e72b1288f65c5a7f2f6c020080af49c8a494ee99ab3eb543
    ota_hash: ccd1069bde76fc2ef3414d619ddb5fb840addae955e85d9829df9a7e8d2484a9
    platform_ref: android-11.0.0_r25
    platform_pubkey: aosp.asc
