version: '12'
name: Android Open Source Project
type: release
variant: user
datetime: 1638999265
host: android
user: build
build_kernel: true
platform:
  extra_remotes:
  - name: grapheneos
    fetch: https://github.com/GrapheneOS
  extra_projects:
  - name: android-prepare-vendor
    groups: device
    path: vendor/android-prepare-vendor
    remote: grapheneos
    revision: 12
  remove_paths:
  - device/generic/car
  - device/generic/mini-emulator-arm64
  - device/generic/mini-emulator-armv7-a-neon
  - device/generic/mini-emulator-x86
  - device/generic/mini-emulator-x86_64
  - device/generic/qemu
  - device/google/atv
  - device/google/contexthub
  - device/google/crosshatch-kernel
  - device/google/muskie
  - device/google/wahoo-kernel
  - platform/developers/demos
  - platform/developers/samples/android
  - platform/prebuilts/qemu-kernel
  - prebuilts/android-emulator
  remove_groups:
  - beagle_x15
  - darwin
  - dragonboard
  - hikey
  - mips
  - poplar
  - yukawa
devices:
  bonito:
    kernel_ref: android-msm-bonito-4.9-android12
    build_id: SQ1A.211205.008
    factory_hash: 4c96f820b8367dac8dbb42b1b9115b2251b610db98b903a6680d145ac12be5fa
    ota_hash: b14d98e399165f2966c23d5a21cb48836a291daa608cc22ec92271e6a62af304
    platform_ref: android-12.0.0_r16
    platform_pubkey: aosp.asc
  sargo:
    kernel_ref: android-msm-bonito-4.9-android12
    build_id: SQ1A.211205.008
    factory_hash: 2358b75baa08a1100a3fb34c18c1affaff613a6d144fdcdcfc281642001d749c
    ota_hash: aba2bb35e02a1ff34506ed8322e2d5e9d85e1d16c48417b604b26fae52cad362
    platform_ref: android-12.0.0_r16
    platform_pubkey: aosp.asc
  crosshatch:
    kernel_ref: android-msm-crosshatch-4.9-android12
    avb_mode: vbmeta_chained
    build_id: SP1A.210812.015
    factory_hash: 6dae03f8e91644f6ee0b9e872faaee2b43312c490f05934940c68074dced303a
    ota_hash: 3f7cc066ac58e8d99bade37fd5d44bbdea6df562077752b47c673d795a2f3b69
    platform_ref: android-12.0.0_r1
    platform_pubkey: aosp.asc
  blueline:
    kernel_ref: android-msm-crosshatch-4.9-android12
    avb_mode: vbmeta_chained
    build_id: SP1A.210812.015
    factory_hash: c5f3469cfd9ac914377eac1d05eb60bde3b88d109c9e618eecf82a938bad5625
    ota_hash: cee465f51c930684b8b2b0354eba2ba83e5001b92c03a74036ccc9ceebd972fb
    platform_ref: android-12.0.0_r1
    platform_pubkey: aosp.asc
